title: JB Manager Dokumentation
description: Eine Dokumentation f√ºr die Anwendung JB Manager
theme: just-the-docs

url: https://jbmanager.github.io/docs

Template Repository: https://github.com/jbmanager/docs
